### ISSUE TITLE
V4 - Requisitos funcionais - ROADMAP

### ISSUE THREAD

**Issue by lucasljj** [lucasljj/bhd8#116]
<h3>Estética e Usabilidade</h3>
- [ ] Garantir que tudo esteja integrado e fácil de usar #67 
- [ ] #12 Ter um novo tema baseado no Material Design
- [ ] Melhorar a página de perfil do usuário #14 
- [x] Mobile First #104 
- [ ] Melhorar a forma que os resultados são exibidos na busca #25 
- [x] Melhorar esteticamente os filtros das views (ex: /hentais, /doujinshis)
- [x] Miniaturas dos próximos episódios/episódios anteriores na lateral #62
- [x] Repensar o modo que listamos o conteúdo #73 (isso e o crunchyroll já influenciaram bastante nos episódios e itens relacionados)
- [ ] Diminuir o intervalo da nota de 10 para 5 (estrelas) #77 

<h3>Migrar dados antigos</h3>
- [ ] #1 Integrar oS leitorES online ao site, "desativar" os scripts antigos
  - [ ] #1 Migrar o conteúdo dos leitores antigos 
  - [x] #2 Usuários poderão baixar o conteúdo de uma revistinha
  - [ ] Escrever um microapp para lidar com as rotas antigas do foolslide (redirecionar para o drupal)

- [ ] #76 Refatorar a nossa estrutura de conteúdo
- [x] #83 Refatorar a taxonomia do site
- [ ] #76 Migrar o conteúdo do site antigo (a v3 em Drupal 7)

<h3>Mantenabilidade</h3>
- [ ] [Tag mantenabilidade](https://github.com/lucasljj/BaixarHentaiD8/labels/mantenabilidade)

<h3>Grandes melhorias no engajamento</h3>
- [ ] #5 Possibilitar que os usuários favoritem o conteúdo

- [ ] #94 Lista "assistir mais tarde"

- [ ] #13 Notificações no site

- [ ] #6 Usar a API dos encurtadores de links para gerar links encurtados (grande melhoria em dispositivos móveis)

- [ ] Melhorar o sistema de comentários #52 

- [ ] Verificador de links, para procurar links quebrados #11

<h2>Não bloqueadores</h2>
<h3>Alguns componentes das questões abaixo serão escritos em outros, portanto isso deve ser adiado para o "final"</h3>
~~Por exemplo, vai ser bem mais fácil fazer o calendário de lançamentos quando eu tiver uma boa ideia de como a API AJAX do Drupal funciona,~~(já saquei) a ideia central do nosso calendário é que os usuários possam ser notificados apóso lançamento de algum item :)
- [ ] Calendário dos próximos lançamentos #10 
- [ ] #34 Ativar o VIP automaticamente após o pagamento
- [ ] Possibilitar a *sugestão* de sinopses pelos usuários #46
- [ ] #7 Upar episódios novos e quebrados automaticamente
- [ ] Módulo de sugestão de alteração dos itens (tags, sinopses, legendas, etc) pelos usuários #72

**Comment by lucasljj** [comment]
Isso vai ser bem útil para ter uma ideia geral de quais áreas do site já estão prontas

**Comment by lucasljj** [comment]
Todas as issues abertas e marcadas com a tag v4 são requisitos funcionais
